name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd src/github-action-demo && cargo build --verbose
    # - name: Run tests
      # run: cd src/github-action-demo && cargo test --verbose
